# Generated by Django 5.0 on 2023-12-19 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("robotic", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roboticuser",
            name="is_professor",
        ),
        migrations.RemoveField(
            model_name="roboticuser",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="roboticuser",
            name="is_student",
        ),
        migrations.AddField(
            model_name="roboticuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("teacher", "Teacher"),
                    ("staff", "Staff"),
                    ("student", "Student"),
                ],
                default="student",
                max_length=10,
            ),
        ),
    ]
