# Generated by Django 4.2.8 on 2024-03-15 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roboticuser',
            name='is_activated_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='roboticuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
    ]
