# Generated by Django 4.2.8 on 2024-03-16 19:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('robotic', '0002_roboticuser_is_activated_by_admin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roboticuser',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.date(2000, 1, 1)),
        ),
        migrations.AlterField(
            model_name='roboticuser',
            name='cpf',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='roboticuser',
            name='full_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='roboticuser',
            name='registration',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='roboticuser',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='robotic.school'),
        ),
        migrations.AlterField(
            model_name='roboticuser',
            name='sex',
            field=models.CharField(blank=True, max_length=1),
        ),
    ]
