# Generated by Django 4.2.8 on 2024-03-15 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotic', '0002_alter_roboticuser_data_nasc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roboticuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='roboticuser',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AlterField(
            model_name='roboticuser',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
