# Generated by Django 5.0.4 on 2024-06-02 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotic', '0002_event_project_usereventassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roboticuser',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
