# Generated by Django 5.0.4 on 2024-07-03 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('robotic', '0003_alter_roboticuser_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificateassignment',
            name='sended',
            field=models.BooleanField(default=False),
        ),
    ]
